swagger: "2.0"
info:
  title: Etalon backend
  description: Advocate etalon backend
  version: 0.0.1
host: localhost
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json

paths:
  /send_message:
    post:
      tags:
      - mail
      summary: Collect's users data
      description: User mail data
      responses:
        200:
          description: successful response
          schema:
            $ref: '#/definitions/Message'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    required:
      - message
      - code
    description: Error message
    properties:
      message:
        type: object
      code:
        type: integer

  Message:
    type: object
    required:
      - message
    properties:
      message:
        type: object