smtp_credentials:
  smtp_host: ''
  smtp_port: 587
  smtp_username: ''
  smtp_password: ''
  smtp_from: ''
  smtp_to: ''
auth_credentials:
  username: ''
  password: ''
  jwt_secret: ''
postgres_config:
  username: ''
  password: ''
  db: ""
  port: 5432
  host: ""