version: '3.8'
services:
  cache:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - cache:/data
  api:
    container_name: bot-forge-back
    build:
      context: ./
      target: production
    image: bot-forge-back
    depends_on:
      - cache
    ports:
      - 8000:8000
    links:
      - cache
    volumes:
      - ./:/src
volumes:
  cache:
    driver: local