version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: advocate
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
  cache:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - cache:/data
  api:
    container_name: advocate-back
    build:
      context: ./
      target: production
    image: advocate-back
    depends_on:
      - cache
    ports:
      - 8000:8000
    links:
      - cache
    volumes:
      - ./:/src
volumes:
  cache:
    driver: local